### ISSUE TITLE
Developer tools for provisioning templates

### ISSUE THREAD

**Issue by ivanvagunin** [OfficeDev/PnP-Provisioning-Templates#2]
Hi @PaoloPia,
I've made a few tools to make it easier to work to develop site templates in Visual Studio. Here is small demo: https://1drv.ms/v/s!Ai_UzU8o9Xv_i7VrlqR5HwMazJXkAA.
I am gonna prepare pull request for Tools repo (looks like it's more suitable for that kind of stuff than this one), but anyway would like to get your feedback on that. Do you think it would be interesting for community to have something like that?
__
Br, Ivan

**Comment by VesaJuvonen** [comment]
That would be absolutely extremely useful and hopefully we can get more people working on these kind of solutions. We do have already one VS extension in the PnP-tools and in optimal situation we should combine this to that one, so that we would only have one PnP VS extension. Right location for these kind of extensions would be that PnP-Tools anyway. Open for suggestion around combining the extensions. Great great suggestion and idea.

**Comment by VesaJuvonen** [comment]
thx @ivanvagunin for the submission around this in the PnP-Tools repository and great to have the video demo also in the SIG recording. I'll close this one from here, since the tooling is already developed and shared.
